export const clues = [
  {
    connection: "Harf sayısının her kelimede bir artması",
    clue1: "O da kim",
    clue2: "Altı kasım gecesi",
    clue3: "Boyalar aromatik görünüyor",
    clue4: "(Örn:) Akrobatik hareketleri göstermiştim",
    questionId: 1,
  },
  {
    connection: "Serdar Ortaç Şarkıları",
    clue1: "Mikrop",
    clue2: "Heyecan",
    clue3: "Mesafe",
    clue4: "Poşet",
    questionId: 2,
  },
  {
    connection: "Musa Çam hakkında ipuçları",
    clue1: "48 dakika",
    clue2: "The Silver Arrows",
    clue3: "65.gün",
    clue4: "Kızıldeniz",
    questionId: 3,
  },
  {
    connection: "Adında 'sarı' geçen şarkılar",
    clue1: "Erzurum çarşı pazar",
    clue2: "Dayanamam kıskanırım",
    clue3: "Genç ömrümün baharı",
    clue4: "Bugün düşerse yarın kalkar",
    questionId: 4,
  },
  {
    connection: "Animasyon filmlerinin ana karakterleri",
    clue1: "Nesli Tükenmiş Hayvanlar",
    clue2: "Oyuncaklar",
    clue3: "Duygularımız",
    clue4: "5 Kişilik Dedektif Grubu",
    questionId: 5,
  },
  {
    connection: "'Teşekkürler' anagramları",
    clue1: "Crime - Fransa",
    clue2: "Naked - Almanya",
    clue3: "Gazier - İtalya",
    clue4: "Agarics - İspanya",
    questionId: 6,
  },
  {
    connection: "Benzer bayraklar",
    clue1: "Çad",
    clue2: "Moldova",
    clue3: "Andorra",
    clue4: "Romanya",
    questionId: 7,
  },
  {
    connection: "Tahmini genetik benzerliklerimiz",
    clue1: "Muz - %41",
    clue2: "Meyve Sineği - %60",
    clue3: "İnek - %80",
    clue4: "Şempanze - %96",
    questionId: 8,
  },
  {
    connection: "Elementler ve sembolleri",
    clue1: "1,5 Radon",
    clue2: "1,4 Terbiyum",
    clue3: "1,3 Magnezyum",
    clue4: "1,2 Helyum",
    questionId: 9,
  },
  {
    connection: "Dart tahtası puanları ve konumları",
    clue1: "Doğu 6",
    clue2: "Güney 3",
    clue3: "Batı 11",
    clue4: "Kuzey 20",
    questionId: 10,
  },
  {
    connection: "Sessiz harfsiz kıtalar (Ei ai ıaa)",
    clue1: "Aa",
    clue2: "Aua",
    clue3: "Aaia",
    clue4: "Ue Aia",
    questionId: 11,
  },
  {
    connection: "Gözbebekleri şekilleri",
    clue1: "At - -",
    clue2: "Mürekkepbalığı w w",
    clue3: "İnsan o o",
    clue4: "Kedi | |",
    questionId: 12,
  },
  {
    connection: "Gece yarısına 1000,100,10,1 dakika kala zamanlar",
    clue1: "7.20 A.M.",
    clue2: "10.20 A.M.",
    clue3: "11.50 P.M.",
    clue4: "11.59 P.M.",
    questionId: 13,
  },
  {
    connection: "Ülke içinde ülke",
    clue1: "FmcR",
    clue2: "IvaT",
    clue3: "IsmT",
    clue4: "ZlsA",
    questionId: 14,
  },
  {
    connection: "Gece yarısına 1000,100,10,1 dakika kala zamanlar",
    clue1: "7.20 A.M.",
    clue2: "10.20 A.M.",
    clue3: "11.50 P.M.",
    clue4: "11.59 P.M.",
    questionId: 15,
  },
  {
    connection: "Yemek adıyla şarkı yapmış olan sanatçılar",
    clue1: "Barış Manço",
    clue2: "Tarık Mengüç",
    clue3: "Mirkelam",
    clue4: "Atilla Taş",
    questionId: 16,
  },
  // {
  //   connection: "",
  //   clue1: "",
  //   clue2: "",
  //   clue3: "",
  //   clue4: "",
  //   questionId: 17,
  // },
];
