export const clues = [
  {
    connection: "Harf sayısının her kelimede bir artması",
    clue1: "O da kim",
    clue2: "Altı kasım gecesi",
    clue3: "Boyalar aromatik görünüyor",
    clue4: "(Örn:) Akrobatik hareketleri göstermiştim",
    questionId: 1,
  },
  {
    connection: "Serdar Ortaç Şarkıları",
    clue1: "Mikrop",
    clue2: "Heyecan",
    clue3: "Mesafe",
    clue4: "Poşet",
    questionId: 2,
  },
  {
    connection: "Musa Çam hakkında ipuçları",
    clue1: "48 dakika",
    clue2: "The Silver Arrows",
    clue3: "65.gün",
    clue4: "Kızıldeniz",
    questionId: 3,
  },
  {
    connection: "Adında 'sarı' geçen şarkılar",
    clue1: "Erzurum çarşı pazar",
    clue2: "Dayanamam kıskanırım",
    clue3: "Genç ömrümün baharı",
    clue4: "Bugün düşerse yarın kalkar",
    questionId: 4,
  },
  {
    connection: "Animasyon filmlerinin ana karakterleri",
    clue1: "Nesli Tükenmiş Hayvanlar",
    clue2: "Oyuncaklar",
    clue3: "Duygularımız",
    clue4: "5 Kişilik Dedektif Grubu",
    questionId: 5,
  },
  {
    connection: "'Teşekkürler' anagramları",
    clue1: "Crime - Fransa",
    clue2: "Naked - Almanya",
    clue3: "Gazier - İtalya",
    clue4: "Agarics - İspanya",
    questionId: 6,
  },
  {
    connection: "Benzer bayraklar",
    clue1: "Çad",
    clue2: "Moldova",
    clue3: "Andorra",
    clue4: "Romanya",
    questionId: 7,
  },
  {
    connection: "Tahmini genetik benzerliklerimiz",
    clue1: "Muz - %41",
    clue2: "Meyve Sineği - %60",
    clue3: "İnek - %80",
    clue4: "Şempanze - %96",
    questionId: 8,
  },
];
